version: "3.9"  # docker-compose 버전 (버전별로 명령어가 다름)
services:
  app:  # 실행할 컨테이너 (app, mysql)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "6000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=karyu
    restart: always

  mysql:
    image: mysql:8.0          # 컨테이너화 할 이미지 (docker hub에서 가져옴)
    container_name: mysql_db
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=karyu
    ports:
      - "63306:3306"
volumes:
  mysqldata: